- group:
    name: bastion
    gid: 2003
    state: present
  tags:
    - bastion

- user:
    name: bastion
    uid: 2003
    group: bastion
    shell: /usr/sbin/nologin
    state: present
    createhome: false
  tags:
    - bastion
    - users

- file:
    path: /opt/bastion/ssh_chroot
    state: directory
    owner: root
    group: wheel
    mode: 0755
  tags:
    - bastion

- file:
    path: /opt/bastion/totp/
    state: directory
    owner: root
    group: wheel
    mode: 0755
  tags:
    - bastion

- file:
    path: /opt/bastion/totp/bastion
    state: directory
    owner: bastion
    group: bastion
    mode: 0700
  tags:
    - bastion

- file:
    path: /opt/bastion/totp/bastion/config
    owner: bastion
    group: bastion
    mode: 0400
  tags:
    - bastion

# It may not be the greatest idea to make this public
# but its not like its supposed to be private
- authorized_key:
    exclusive: yes
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFBbue/RQS6f3KQDQUUXXLj2gQ/Ga6QDODsTfqhj3JP7 eax"
    key_options:
    manage_dir: yes
    path: /opt/bastion/authorized_keys/bastion
    user: bastion
    state: present
  tags:
    - configuration
    - bastion

- name: configure pam
  copy:
    src: sshd_pam_config
    dest: /etc/pam.d/sshd
    owner: root
    group: wheel
    mode: 0644
  tags:
    - configuration
    - bastion

- sysrc:
    name: sshd_enable
    value: yes
    state: present
  tags:
    - configuration
    - bastion
