- group:
    name: bastion
    gid: 2003
    state: present

- user:
    name: bastion
    uid: 2003
    group: bastion
    shell: /usr/sbin/nologin
    state: present
    createhome: false

- file:
    path: /opt/bastion/ssh_chroot
    state: directory
    owner: root
    group: wheel
    mode: 0755

- file:
    path: /opt/bastion/totp/
    state: directory
    owner: root
    group: wheel
    mode: 0755

- file:
    path: /opt/bastion/totp/bastion
    state: directory
    owner: bastion
    group: bastion
    mode: 0700

- file:
    path: /opt/bastion/totp/bastion/config
    owner: bastion
    group: bastion
    mode: 0400

# It may not be the greatest idea to make this public
# but its not like its supposed to be private
- authorized_key:
    exclusive: yes
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFBbue/RQS6f3KQDQUUXXLj2gQ/Ga6QDODsTfqhj3JP7 eax"
    key_options:
    manage_dir: yes
    path: /opt/bastion/authorized_keys/bastion
    user: bastion
    state: present

#- name: Insert TOTP before primary auth
#  pamd:
#    name: sshd
#    type: auth
#    control: required
#    module_path: pam_unix.so
#    new_type: auth
#    new_control: required
#    new_module_path: pam_google_authenticator.so
#    state: after
#
#- name: Ensure TOTP has correct arguments
#  pamd:
#    name: sshd
#    type: auth
#    control: required
#    module_path: pam_google_authenticator.so
#    module_arguments: 'secret=/opt/bastion/totp/${USER}/config debug echo_verification_code'
#    state: args_present

- name: Remove password prompt
  pamd:
    name: sshd
    type: auth
    control: required
    module_path: pam_unix.so
    new_type: auth
    state: absent

- name: Install bastion packages
  pkgng:
    name:
      - pam_google_authenticator
    state: present
  tags:
    - packages

- sysrc:
    name: sshd_enable
    value: yes
    state: present
  tags:
    - configuration
