---
- name: add python if not installed
  hosts: all
  gather_facts: False

  pre_tasks:
    - name: install python
      raw: test -e /usr/local/bin/python || env ASSUME_ALWAYS_YES=yes pkg install python27
      changed_when: False

- name: apply to host system
  hosts: fasteagle
  roles:
    - base
    - storage
    - human
    - eaxhome
    - willshersystems.sshd

- name: create ssh bastion
  hosts: bastion
  roles:
    - sshd
    - bastion
    - willshersystems.sshd

- name: create development machine
  hosts: develop
  roles:
    - sshd
    - human
    - eaxhome
    - develop
    - willshersystems.sshd

- name:
  hosts: vpn
  roles:
    - vpn

- name: apply to everything
  hosts: all

  roles:
    - common
