---
- name: ensure jail has networking
  hosts: bastion
  gather_facts: False

  pre_tasks:
    - name: run dhclient
      raw: /sbin/dhclient vnet0
      changed_when: False

  ignore_errors: true

- name: add python if not installed
  hosts: all
  gather_facts: False

  pre_tasks:
    - name: install python
      raw: test -e /usr/local/bin/python || env ASSUME_ALWAYS_YES=yes pkg install python37
      changed_when: False

#- name: gather facts
#  hosts: all
#  tasks:
#    - name: Gathering facts
#      setup:

- name: apply to everything
  hosts: all
  roles:
    - common

- name: apply to host system
  hosts: fasteagle
  roles:
    - base
    - storage
    - human
    - eaxhome
    - willshersystems.sshd
    - power
    - audit
    - develop
    - downloader
    - toolspage
    - audiovideo

- name: create ssh bastion
  hosts: bastion
  roles:
    - sshd
    - bastion
    - willshersystems.sshd
    - audit

- name: create laptop
  hosts: freeingeagle
  roles:
    - human
    - eaxhome
    - desktop
    - interactive
    - power
