---
- name: apply to host system
  hosts: fasteagle

  roles:
    - base
    - storage
    - common
    - human
    - eaxhome
    - develop
    - willshersystems.sshd

- name: apply to everything
  hosts: all

  roles:
    - common
