---
- name: power down unused devices
  sysctl:
    name: hw.pci.do_power_nodriver
    value: "3"
    sysctl_set: yes
    state: present
  tags:
    - power
    - hardware
    - configuration

- name: permit lower power usage
  sysctl:
    name: hw.acpi.cpu.cx_lowest
    value: "C3"
    state: present
  tags:
    - power
    - hardware
    - configuration

- name: set power related configuration
  sysrc:
    name: "{{ item }}"
    value: "YES"
    state: present
  loop:
    - powerd_enable
  tags:
    - power
    - configuration
    - services
