all:
  children:
    base:
      hosts:
        fasteagle:
          ansible_host: localhost
      vars:
        ansible_user: eax
        ansible_connection: local
    jails:
      hosts:
        bastion:
          ansible_host: ioc-bastion
        vpn:
          ansible_host: ioc-vpn
        znc:
          ansible_host: ioc-znc
      vars:
        ansible_connection: jail
  vars:
    ansible_python_interpreter: /usr/local/bin/python3.6
