- name: Install interactive packages
  pkgng:
    name:
      - xorg-minimal
      - i3
      - i3status
      - xscreensaver
      - rxvt-unicode
      - xbindkeys
      - xclip
    autoremove: yes
    state: present

- name: Permit 'zapping' X
  template:
    src: xorg.conf.d/zap.conf
    dest: /usr/local/etc/X11/xorg.conf.d/zap.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes

- name: add basic rc.conf values
  blockinfile:
    path: /etc/rc.conf
    backup: yes
    block: |
      ifconfig_re0="SYNCDHCP inet6 accept_rtadv"
      syslogd_flags="-ss"
      local_unbound_enable="YES"
      moused_enable="YES"
      ntpd_enable="YES"
      dumpdev="AUTO"
      zfs_enable="YES"
    create: yes
    owner: root
    group: wheel
    marker: "# {mark} ANSIBLE MANAGED BLOCK :: basic"
    state: present

- name: add interactive rc.conf values but permit customization
  blockinfile:
    path: /etc/rc.conf
    backup: yes
    block: |
      kld_list="/boot/modules/i915kms filemon cpuctl coretemp acpi_video if_iwm"
      linux_enable="YES"
      dbus_enable="YES"
      hald_enable="YES"
    create: yes
    owner: root
    group: wheel
    marker: "# {mark} ANSIBLE MANAGED BLOCK :: interactive"
    state: present

- name: set up loader.conf
  blockinfile:
    path: /boot/loader.conf
    backup: yes
    block: |
      # Auto switch between headphone and speaker
      hint.hdaa.0.nid20.config="as=1 seq=0"
      hint.hdaa.0.nid21.config="as=1 seq=15"
    create: yes
    owner: root
    group: wheel
    state: present
