- group:
    name: ssh_allowed
    gid: 2001
    state: present

- group:
    name: eax
    gid: 1001
    state: present

- user:
    name: eax
    uid: 1001
    group: eax
    groups: eax,wheel,ssh_allowed,audit
    home: /home/eax
    shell: /usr/local/bin/zsh
    state: present

- name: create .ssh directory for later use
  file:
    path: /home/eax/.ssh
    state: directory
    owner: eax
    group: eax
    mode: 0700

- name: Allow wheel users to sudo
  lineinfile:
    dest: /usr/local/etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
