- name: Install development packages
  pkgng:
    name:
      - ripgrep
      - the_silver_searcher
      - ghc
      - docproj
      - ninja
      - cpuid
      - distilator
      - portlint
      - ruby25
      - valgrind
      - subversion
      - cvs
      - hs-ShellCheck
    autoremove: yes
    state: present

- name: Remove packages I don't want
  pkgng:
    name:
      - ccache
    autoremove: yes
    state: absent

- name: create main mountpoints for source code
  file:
    path: "{{ item }}"
    owner: eax
    group: eax
    mode: "0755"
    state: directory
  with_items:
    - /srv/src
    - /srv/rosrc
    - /srv/obj

- name: mount read-only copy of source
  mount:
    path: /srv/rosrc
    src: /srv/src
    fstype: nullfs
    opts: ro,late,noauto
    state: mounted

- name: Build FreeBSD with special options
  template:
    src: src.conf
    dest: /etc/src.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes

- name: set up /etc/make.conf
  template:
    src: make.conf
    dest: /etc/make.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes

- name: set up /etc/src-env.conf
  template:
    src: src-env.conf
    dest: /etc/src-env.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes

- name: set up /usr/local/etc/ccache.conf
  template:
    src: ccache.conf
    dest: /usr/local/etc/ccache.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes
