- name: Install programming languages and compilers
  pkgng:
    name:
      - ruby
      - ghc
      - gcc7
      - gcc9-devel
      - perl5
      - php72
      - R
      - scala
      - swi-pl
      - go
      - iverilog
  ignore_errors: True
  tags:
    - packages
    - python

- name: Install development packages
  pkgng:
    name:
      - ripgrep
      - the_silver_searcher
      - docproj
      - ninja
      - cpuid
      - distilator
      - portlint
      - valgrind
      - subversion
      - cvs
      - hs-ShellCheck
      - mercurial
      - qemu
      - pkg-provides
      - graphviz
      - dmidecode
      - mtr
      - lsof
      - hub
      - cmake
      - rsync
      - php72-curl
      - php72-json
      - php72-simplexml
      - py36-pycodestyle
      - py36-autopep8
      - pciutils
      - py36-asciinema
      - gdb
      - sbt
      - py36-virtualenv
      - gmake
      - groff
      - texinfo # for makeinfo for gdb compilation
      - htop
      - gnupg
      - bind-tools
      - ccache
      - autotools
      - wget
      - kyua
      - cloc
      - diffstat
      - transmission-cli
    state: present
  ignore_errors: True
  tags:
    - packages
    - qemu
    - python

- name: Install package managers
  ignore_errors: True
  pkgng:
    name:
      - ruby25-gems
      - lua53-luarocks
      - yarn
      - py36-pip
      - stack
      - npm
  tags:
    - packages
    - qemu
    - python

- name: Remove packages I don't want
  pkgng:
    name:
      - perl5.24
      - perl5.26
    autoremove: yes
    state: absent
  tags:
    - packages
    - cleanup

- name: create main mountpoints for source code
  file:
    path: "{{ item }}"
    owner: eax
    group: eax
    mode: "0755"
    state: directory
  loop:
    - /srv/src
    - /srv/rosrc
    - /srv/obj
    - /srv/cores
  tags:
    - sourcecode

- name: mount read-only copy of source
  mount:
    path: /srv/rosrc
    src: /srv/src
    fstype: nullfs
    opts: ro,late
    state: mounted
  tags:
    - sourcecode

- name: Build FreeBSD with special options
  copy:
    src: src.conf
    dest: /etc/src.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes
  tags:
    - freebsdbuild

- name: set up /etc/make.conf
  copy:
    src: make.conf
    dest: /etc/make.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes
  tags:
    - freebsdbuild

- name: set up /etc/src-env.conf
  copy:
    src: src-env.conf
    dest: /etc/src-env.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes
  tags:
    - freebsdbuild

- name: set up /usr/local/etc/ccache.conf
  template:
    src: ccache.conf.j2
    dest: /usr/local/etc/ccache.conf
    owner: nobody
    group: nobody
    mode: '0644'
    backup: yes
  tags:
    - configuration

- name: Set up pkgng configuration
  copy:
    src: pkg.conf
    dest: /usr/local/etc/pkg.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes
  tags:
    - configuration

- import_tasks: poudriere.yml
- import_tasks: qemu_jail.yml
- import_tasks: nginx.yml
