- name: Install packages required for nginx
  pkgng:
    name:
      - nginx-devel
    state: present
  tags:
    - packages
    - nginx

- name: set up nginx root config
  copy:
    src: nginx.conf
    dest: /usr/local/etc/nginx/nginx.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes
  notify:
    - restart nginx
  tags:
    - configuration
    - nginx

- name: create sites-enabled directory
  file:
    name: /usr/local/etc/nginx/sites-enabled
    state: directory
  tags:
    - configuration
    - nginx

- name: create www serving directory
  file:
    name: /srv/www
    state: directory
    owner: eax
    group: eax
    mode: 0755
  tags:
    - configuration
    - nginx

- name: set up nginx root config
  copy:
    src: devbox.conf
    dest: /usr/local/etc/nginx/sites-enabled/devbox.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes
  notify:
    - restart nginx
  tags:
    - configuration
    - nginx

- name: ensure nginx is started (and enable at boot)
  service:
    name: nginx
    state: started
    enabled: yes
  tags:
    - nginx
