- name: Install packages required for poudriere
  pkgng:
    name:
      - poudriere
      - ports-mgmt/dialog4ports
    state: present
  tags:
    - packages
    - poudriere

- name: set up poudriere.conf
  template:
    src: poudriere.conf
    dest: /usr/local/etc/poudriere.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes
  tags:
    - configuration
    - poudriere

- sysrc:
    name: poudriered
    value: YES
    state: present
  tags:
    - configuration
    - services
    - poudriere
