- name: Install packages required for poudriere
  pkgng:
    name:
      - poudriere-devel
      - dialog4ports
    state: present
  tags:
    - packages
    - poudriere

- name: set up poudriere.conf
  template:
    src: poudriere.conf.j2
    dest: /usr/local/etc/poudriere.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes
  tags:
    - configuration
    - poudriere

- sysrc:
    name: poudriered
    value: YES
    state: present
  tags:
    - configuration
    - services
    - poudriere

- name: ensure that ccache directory exists for poudriere
  file:
    path: /srv/obj/ccache-poudriere
    state: directory
    owner: nobody
    group: nobody
  tags:
    - poudriere

- name: set up poudriere ccache config
  template:
    src: ccache.conf.j2
    dest: /srv/obj/ccache-poudriere/ccache.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes
  vars:
    sloppiness: file_macro,time_macros
  tags:
    - configuration
    - poudriere

- name: ensure that distfile directory exists for poudriere
  file:
    path: /srv/obj/distfiles
    state: directory
  tags:
    - poudriere

- name: poudriere make.conf
  copy:
    src: poudriere_default_make.conf
    dest: /usr/local/etc/poudriere.d/make.conf
    owner: root
    group: wheel
    mode: '0500' # -r-x------
    backup: yes
  tags:
    - configuration
    - poudriere
