- debug:
    var: vars
    verbosity: 3

- name: Set up repository path
  template:
    src: FreeBSD.conf
    dest: /usr/local/etc/pkg/repos/FreeBSD.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes

- name: Install basic packages
  pkgng:
    name:
      - ansible
      - bash
      - git
      - jq
      - tmux
      - vim
      - sudo
      - python3
      - zsh
    autoremove: yes
