- debug:
    var: vars
    verbosity: 3

- name: Set up repository path
  template:
    src: FreeBSD.conf
    dest: /usr/local/etc/pkg/repos/FreeBSD.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes

- name: Install basic packages
  pkgng:
    name:
      - ansible
      - bash
      - git
      - rubygem-ohai
      - jq
      - tmux
      - vim
      - sudo
      - python3
      - pam_google_authenticator
      - zsh
    autoremove: yes

- name: Setup production malloc
  file:
    dest: /etc/malloc.conf
    src: 'abort:false,junk:false'
    force: yes
    state: link
    owner: root
    group: wheel
    mode: 644
