- debug:
    var: vars
    verbosity: 3
  tags:
    - debug

- name: Ensure respository directory exists
  file:
    path: /usr/local/etc/pkg/repos
    recurse: yes
    state: directory
  tags:
    - configuration

- name: Set up repository path
  copy:
    src: FreeBSD.conf
    dest: /usr/local/etc/pkg/repos/FreeBSD.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes
  tags:
    - configuration

- name: Install basic packages
  pkgng:
    name:
      - bash
      - cowsay
      - git-subversion
      - rubygem-ohai
      - jq
      - tmux
      - vim
      - sudo
      - python3
      - pam_google_authenticator
      - zsh
      - vuxml
    autoremove: yes
    state: present
  tags:
    - packages

#- name: Setup production malloc
#  file:
#    dest: /etc/malloc.conf
#    src: 'abort:false,junk:false'
#    force: yes
#    state: link
#    owner: root
#    group: wheel
#    mode: '0644'
#  tags:
#    - configuration
#
- name: Ensure some packages are not installed
  pkgng:
    name:
      - sl
    autoremove: yes
    state: absent
  tags:
    - cleanup

- sysrc:
    name: syslogd_flags
    state: present
    value: -ss
  tags:
    - configuration

- sysrc:
    name: zfs_enable
    state: present
    value: yes
  tags:
    - configuration

- sysrc:
    name: hostname
    value: "{{ inventory_hostname }}"
    state: present
  tags:
    - configuration

- service:
    name: syslogd
    state: started
  tags:
    - services
