- name: Set up repository path
  template:
    src: FreeBSD.conf
    dest: /usr/local/etc/pkg/repos/FreeBSD.conf
    owner: root
    group: wheel
    mode: 644
    backup: yes

- name: Install basic packages
  pkgng:
    name:
      - python3
    autoremove: yes
