- debug:
    var: vars
    verbosity: 3

- name: Ensure respository directory exists
  file:
    path: /usr/local/etc/pkg/repos
    recurse: yes
    state: directory

- name: Set up repository path
  template:
    src: FreeBSD.conf
    dest: /usr/local/etc/pkg/repos/FreeBSD.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes

- name: Install basic packages
  pkgng:
    name:
      - ansible
      - bash
      - cowsay
      - git
      - rubygem-ohai
      - jq
      - tmux
      - vim
      - sudo
      - python3
      - pam_google_authenticator
      - zsh
      - vuxml
    autoremove: yes
    state: present

- name: Setup production malloc
  file:
    dest: /etc/malloc.conf
    src: 'abort:false,junk:false'
    force: yes
    state: link
    owner: root
    group: wheel
    mode: 644

- name: Ensure some packages are not installed
  pkgng:
    name:
      - sl
    autoremove: yes
    state: absent

- sysrc:
    name: syslogd_flags
    state: present
    value: -ss

- sysrc:
    name: zfs_enable
    state: present
    value: yes

- sysrc:
    name: hostname
    value: "{{ inventory_hostname }}"
    state: present

- service:
    name: syslogd
    state: started
