---

- name: create src dirs
  zfs:
    name: "{{ item }}"
    state: present
    extra_zfs_properties:
      atime: off
      exec: on
      redundant_metadata: all
  loop:
    - zroot/srv/src
    - zroot/usr/src
  tags:
    - storage
    - zfs

- zfs:
    name: "{{ item }}"
    state: present
    extra_zfs_properties:
      atime: off
      exec: on
      redundant_metadata: most
      sync: disabled
  loop:
    - zroot/srv/obj
    - zroot/srv/obj/ccache
  tags:
    - storage
    - zfs

- zfs:
    name: zroot/srv/cores
    state: present
    extra_zfs_properties:
      atime: off
      exec: on
      redundant_metadata: all
  tags:
    - storage
    - zfs

- zfs:
    name: zroot/srv/cores
    state: present
    extra_zfs_properties:
      atime: off
      exec: on
      redundant_metadata: all
  tags:
    - storage
    - zfs

- name: add cron for zfs snapshotting
  copy:
    src: zfs_auto_snapshot.crontab
    dest: /etc/cron.d/zfs_auto_snapshot
    mode: '0644'
    owner: root
    group: wheel
    backup: no
  tags:
    - configuration
    - zfs
