---
- zfs_facts:
    name: zroot/code/obj
  register: zrootcodeobj_exists
  ignore_errors: True

- zfs:
    name: zroot/code/obj
    state: present
    atime: off
    canmount: on
    checksum: on
    compress: on
    exec: on
    mountpoint: /srv/obj
    readonly: off
    redundant_metadata: most
    logbias: throughput
    sync: disabled
  when: zrootcodeobj_exists|failed

- zfs_facts:
    name: zroot/code/obj@empty
  register: zrootcodeobj_empty_exists
  ignore_errors: True

- zfs:
    name: zroot/code/obj@empty
    state: present
  when: zrootcodeobj_empty_exists|failed

- zfs_facts:
    name: zroot/code/src
  register: zrootcodesrc_exists
  ignore_errors: True

- zfs:
    name: zroot/code/src
    state: present
    atime: off
    canmount: on
    checksum: on
    compress: on
    exec: on
    mountpoint: /srv/src
    readonly: off
    redundant_metadata: all
    logbias: latency
    sync: disabled
    utf8only: on
  when: zrootcodesrc_exists|failed
