---

- name: create src dirs
  zfs:
    name: "{{ item }}"
    state: present
    extra_zfs_properties:
      atime: off
      exec: on
      redundant_metadata: all
  loop:
    - zroot/srv/src
    - zroot/usr/src
  tags:
    - storage
    - zfs

- zfs:
    name: zroot/srv/obj
    state: present
    extra_zfs_properties:
      atime: off
      exec: on
      redundant_metadata: most
      sync: off
- zfs:
    name: zroot/srv/cores
    state: present
    extra_zfs_properties:
      atime: off
      exec: on
      redundant_metadata: all
  tags:
    - storage
    - zfs
