---

- name: configure auto-snapshots globally
  zfs:
    name: "{{ item }}"
    state: present
    extra_zfs_properties:
      com.sun:auto-snapshot: true
      quota: 200G
  loop:
    - zroot/srv/src
    - zroot/usr/src
  tags:
    - configuration
    - zfs

- name: create src dirs
  zfs:
    name: "{{ item }}"
    state: present
    extra_zfs_properties:
      atime: off
      exec: on
      redundant_metadata: all
      quota: 200G
  loop:
    - zroot/srv/src
    - zroot/usr/src
  tags:
    - storage
    - zfs

- name: configure object directories
  zfs:
    name: "{{ item }}"
    state: present
    extra_zfs_properties:
      atime: off
      exec: on
      redundant_metadata: most
      sync: disabled
      quota: 400G
  loop:
    - zroot/srv/obj
    - zroot/srv/obj/ccache
  tags:
    - storage
    - zfs

- name: configure download directories
  zfs:
    name: "{{ item }}"
    state: present
    extra_zfs_properties:
      atime: off
      exec: on
      redundant_metadata: most
      quota: 400G
  loop:
    - zroot/srv/download
    - zroot/srv/download/transmission
  tags:
    - storage
    - zfs

- name: configure download directories permissions
  file:
    name: /srv/download
    owner: eax
    group: eax
  tags:
    - storage
    - zfs

- name: configure transmission directories
  file:
    name: /srv/download/transmission
    owner: transmission
    group: transmission
  tags:
    - storage
    - zfs
    - transmission

- name: configure coredump directories
  zfs:
    name: zroot/srv/cores
    state: present
    extra_zfs_properties:
      atime: off
      exec: on
      redundant_metadata: all
      quota: 150G
  tags:
    - storage
    - zfs

- name: configure coredump directories permissions
  file:
    name: /srv/cores
    owner: root
    group: wheel
    mode: 01777
  tags:
    - storage
    - zfs

- name: set quota for some datasets
  zfs:
    name: "{{ item.name }}"
    state: present
    extra_zfs_properties:
      quota: "{{ item.quota }}"
  loop:
    - { name: zroot/ROOT, quota: 400G }
    - { name: zroot/iocage/jails, quota: 700G }
    - { name: zroot/iocage/jails/bastion, quota: 10G }
    - { name: zroot/tmp, quota: 300G }
    - { name: zroot/usr/ports, quota: 10M } # avoid using it
    - { name: zroot/var/mail, quota: 1G }
    - { name: zroot/var/tmp, quota: 300G }
    - { name: zroot/srv, quota: 800G }
  tags:
    - zfs

- name: add cron for zfs snapshotting
  copy:
    src: zfs_auto_snapshot.crontab
    dest: /etc/cron.d/zfs_auto_snapshot
    mode: '0644'
    owner: root
    group: wheel
    backup: no
  tags:
    - configuration
    - zfs
