---
- name: Ensure logs rotate
  template:
    src: audit_warn
    dest: /etc/security/audit_warn
    owner: root
    group: wheel
    mode: '0500' # -r-x------
    backup: yes
  tags:
    - configuration
    - audit

- name: Set up audit configuration
  template:
    src: audit_control
    dest: /etc/security/audit_control
    owner: root
    group: wheel
    mode: '0600'
    backup: yes
  tags:
    - configuration
    - audit

- name: Set up audit users conig
  template:
    src: audit_user
    dest: /etc/security/audit_user
    owner: root
    group: wheel
    mode: '0600'
    backup: yes
  tags:
    - configuration
    - audit

- name: rotate audit logs regularly
  cron:
    name: rotate audit logs regularly
    backup: yes
    cron_file: audit_rotate_log
    disabled: no
    env: no
    job: "/usr/sbin/audit -n"
    special_time: hourly
    user: root
    state: present
  tags:
    - configuration
    - cron
    - audit

#- name: ensure the service is running
#  service:
#    name: auditd
#    enabled: yes
#    state: started
#  tags:
#    - services
#    - audit
