---
- sysctl:
    name: kern.randompid
    value: 1
    state: present

- sysctl:
    name: kern.msgbuf_show_timestamp
    value: 1
    state: present

- sysctl:
    name: security.bsd.stack_guard_page
    value: 1
    state: present

- sysctl:
    name: debug.kdb.break_to_debugger
    value: 1
    state: present

- name: ensure proc is mounted
  mount:
    path: /proc
    fstype: procfs
    src: proc
    opts: rw
    state: mounted

- name: Install packages useful for base
  pkgng:
    name:
      - ansible
      - zfs-stats
      - devcpu-data
    autoremove: yes
    state: present
  tags:
    - packages

# --- vinet + jails ---

- sysctl:
    name: net.inet.ip.forwarding
    value: 1
    state: present
  tags:
    - configuration
    - networking

- sysctl:
    name: net.link.bridge.pfil_onlyip
    value: 0
    state: present
  tags:
    - configuration
    - networking

- sysctl:
    name: net.link.bridge.pfil_bridge
    value: 0
    state: present
  tags:
    - configuration
    - networking

- sysctl:
    name: net.link.bridge.pfil_member
    value: 0
    state: present
  tags:
    - configuration
    - networking

- name: ensure fdesc is mounted
  mount:
    path: /dev/fd
    fstype: fdescfs
    src: fdescfs
    opts: rw
    state: mounted

- kld:
    name: "{{ item }}"
    load: true
    boot: false
  tags:
    - configuration
    - hardware
  with_items:
    - cpuctl
    - dtraceall
    - hwpmc
    - filemon
    - if_tap
    - amdtemp
    - tmpfs
    - linux
    - linux64
    - pf
    - nullfs
    - intpm
    - linprocfs

- sysrc:
    name: microcode_update_enable
    value: YES
    state: present
  tags:
    - configuration
    - hardware

- service:
    name: iocage
    state: started
  tags:
    - services
# --- Host configuration ---
- name: Base host configuration options
  template:
    src: src.conf
    dest: /etc/src.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes
  tags:
    - configuration

- name: add basic rc.conf values
  blockinfile:
    path: /etc/rc.conf
    backup: yes
    block: |
      syslogd_flags="-ss"
      hostname="fasteagle"
      ifconfig_igb0="DHCP"
      ifconfig_igb0_ipv6="inet6 accept_rtadv"
      local_unbound_enable="YES"
      sshd_enable="YES"
      moused_enable="YES"
      ntpd_enable="YES"
      dumpdev="AUTO"
      cloned_interfaces="bridge0 bridge1"
      ifconfig_bridge0="addm igb0 up"
      iocage_enable="YES"
      kld_list="cpuctl dtraceall hwpmc filemon if_tap amdtemp tmpfs linux linux64 pf nullfs intpm"
    create: yes
    owner: root
    group: wheel
    marker: "# {mark} ANSIBLE MANAGED BLOCK :: basic"
    state: present
  notify:
    - restart kld
  tags:
    - configuration
    - networking

- name: set up console and boot options
  blockinfile:
    path: /boot/loader.conf
    backup: yes
    block: |
      boot_multicons="YES"
      boot_serial="YES"
      comconsole_speed="115200"
      console="comconsole,vidconsole"
    create: yes
    owner: root
    group: wheel
    state: present
    marker: "# {mark} ANSIBLE MANAGED BLOCK :: console"
  tags:
    - configuration

- include_tasks: qemu_host.yml
