---
- sysctl:
    name: kern.randompid
    value: 1
    state: present

- sysctl:
    name: kern.msgbuf_show_timestamp
    value: 1
    state: present

- sysctl:
    name: security.bsd.stack_guard_page
    value: 1
    state: present

- sysctl:
    name: debug.kdb.break_to_debugger
    value: 1
    state: present

- sysctl:
    name: kern.capmode_coredump
    value: 1
    state: present

- name: ensure proc is mounted
  mount:
    path: /proc
    fstype: procfs
    src: proc
    opts: rw,late
    state: mounted

- name: ensure linsysfs is mounted
  mount:
    path: /compat/linux/sys
    fstype: linsysfs
    src: linsysfs
    opts: rw,late
    state: mounted

- name: ensure linproc is mounted
  mount:
    path: /compat/linux/proc
    fstype: linprocfs
    src: linproc
    opts: rw,late
    state: mounted

- name: Install packages useful for base
  pkgng:
    name:
      - ansible
      - zfs-stats
      - devcpu-data
      - xmbmon
      - bsdhwmon
    state: present
  tags:
    - packages

- name: ensure fdesc is mounted
  mount:
    path: /dev/fd
    fstype: fdescfs
    src: fdescfs
    opts: rw,late
    state: mounted

- name: Load kernel modules
  kld:
    name: "{{ item }}"
    load: True
    boot: False
  tags:
    - configuration
    - hardware
  loop:
    - cpuctl
    - dtraceall
    - hwpmc
    - filemon
    - if_tap
    - amdtemp
    - tmpfs
    - linux
    - linux64
    - pf
    - nullfs
    - intpm
    - linprocfs
    - smbus
    - ksyms
    - vmm
    - nmdm
    - efirt
    - pflog
    - siftr
    - cryptodev

- sysrc:
    name: microcode_update_enable
    value: YES
    state: present
  tags:
    - configuration
    - hardware

# --- Host configuration ---
- name: configure rc.conf
  blockinfile:
    path: /etc/rc.conf
    backup: yes
    block: |
      syslogd_flags="-ss"
      hostname="fasteagle"
      ifconfig_igb0="DHCP"
      ifconfig_igb0_ipv6="inet6 accept_rtadv"
      rtsold_enable="YES"
      local_unbound_enable="YES"
      sshd_enable="YES"
      moused_enable="YES"
      ntpd_enable="YES"
      dumpdev="AUTO"
      # bridge0 - master bridge
      # bridge1 - jails
      # bridge2 - bhyve
      cloned_interfaces="bridge0 bridge1 bridge2 tap0"
      ifconfig_bridge0="addm igb0 up"
      iocage_enable="YES"
      powerd_enable="YES"
      kld_list="cpuctl dtraceall hwpmc filemon if_tap amdtemp tmpfs linux linux64 pf nullfs intpm smbus ksyms vmm nmdm efirt pflog siftr cryptodev"
    create: yes
    owner: root
    group: wheel
    marker: "# {mark} ANSIBLE MANAGED BLOCK :: basic"
    state: present
  notify:
    - restart kld
  tags:
    - configuration
    - networking

- name: syslog logging config
  template:
    src: syslog.conf
    dest: /etc/syslog.conf
    owner: root
    group: wheel
    mode: '0500' # -r-x------
    backup: yes
  tags:
    - configuration
    - logging

#- name: set up console and boot options
#  blockinfile:
#    path: /boot/loader.conf
#    backup: yes
#    block: |
#      boot_multicons="YES"
#      boot_serial="YES"
#      comconsole_speed="115200"
#      console="comconsole,efi"
#    create: yes
#    owner: root
#    group: wheel
#    state: present
#    marker: "# {mark} ANSIBLE MANAGED BLOCK :: console"
#  tags:
#    - configuration
#
- import_tasks: qemu_host.yml
- import_tasks: jails.yml
- import_tasks: monitoring.yml
