---
- sysctl:
    name: kern.randompid
    value: 1
    state: present

- sysctl:
    name: security.bsd.stack_guard_page
    value: 1
    state: present

- name: ensure proc is mounted
  mount:
    path: /proc
    fstype: procfs
    src: proc
    opts: rw
    state: mounted

- name: Install packages useful for base
  pkgng:
    name:
      - ansible
      - zfs-stats
    autoremove: yes
    state: present
  tags:
    - packages

# --- vinet + jails ---

- sysctl:
    name: net.inet.ip.forwarding
    value: 1
    state: present
  tags:
    - configuration
    - networking

- sysctl:
    name: net.link.bridge.pfil_onlyip
    value: 0
    state: present
  tags:
    - configuration
    - networking

- sysctl:
    name: net.link.bridge.pfil_bridge
    value: 0
    state: present
  tags:
    - configuration
    - networking

- sysctl:
    name: net.link.bridge.pfil_member
    value: 0
    state: present
  tags:
    - configuration
    - networking

- name: ensure fdesc is mounted
  mount:
    path: /dev/fd
    fstype: fdescfs
    src: "null"
    opts: rw
    state: mounted

- kld:
    name: amdtemp
    load: true
    boot: false
  tags:
    - configuration
    - hardware

- sysrc:
    name: ifconfig_bridge0
    value: "addm bge0 up"
    state: present
  tags:
    - configuration
    - networking

# --- Host configuration ---
- name: Base host configuration options
  template:
    src: src.conf
    dest: /etc/src.conf
    owner: root
    group: wheel
    mode: '0644'
    backup: yes
  tags:
    - configuration

- name: add basic rc.conf values
  blockinfile:
    path: /etc/rc.conf
    backup: yes
    block: |
      syslogd_flags="-ss"
      hostname="fasteagle"
      ifconfig_igb0="DHCP"
      ifconfig_igb0_ipv6="inet6 accept_rtadv"
      local_unbound_enable="YES"
      sshd_enable="YES"
      moused_enable="YES"
      ntpd_enable="YES"
      dumpdev="AUTO"
      zfs_enable="YES"
      cloned_interfaces="bridge0 bridge1"
      ifconfig_bridge0="addm bge0 up"
      kld_list="cpuctl dtraceall hwpmc filemon if_tap amdtemp"
    create: yes
    owner: root
    group: wheel
    marker: "# {mark} ANSIBLE MANAGED BLOCK :: basic"
    state: present
  tags:
    - configuration

- include_tasks: qemu_host.yml
