---
- name: Install packages for monitoring
  pkgng:
    name:
      - telegraf
      - influxd
      - kapacitor
      - smartmontools
    state: present
  tags:
    - packages
    - monitoring
  
- name: Configure montitoring services
  sysrc:
    name: "{{ item }}_enable"
    value: YES
    state: present
  loop:
    - telegraf
    - influxd
    - kapacitor
  tags:
    - configuration
    - monitoring

- name: allow telegraf to do useful things
  blockinfile:
    path: /usr/local/etc/sudoers
    backup: yes
    block: |
      daemon ALL=(root) NOPASSWD: /usr/local/sbin/smartctl --scan
    create: yes
    owner: root
    group: wheel
    marker: "# {mark} ANSIBLE MANAGED BLOCK :: monitoring"
    validate: 'visudo -cf %s'
    state: present
  tags:
    - configuration
    - monitoring

- name: install telegraf conf
  template:
    src: telegraf.conf
    dest: /usr/local/etc/telegraf.conf
    owner: root
    group: wheel
    mode: '0555'
    backup: yes
    variable_start_string: 'dont-do-anything-with-template-beyond-copy'
    variable_end_string: 'dont-do-anything-with-template-beyond-copy'
  tags:
    - configuration
    - monitoring

- name: install influxd conf
  template:
    src: influxd.conf
    dest: /usr/local/etc/influxd.conf
    owner: root
    group: wheel
    mode: '0555'
    backup: yes
  tags:
    - configuration
    - monitoring
