---
- name: Install packages for monitoring
  pkgng:
    name:
      - telegraf
      - influxdb
      - kapacitor
    state: present
  tags:
    - packages
    - monitoring
  
- name: Configure montitoring services
  sysrc:
    name: "{{ item }}_enable"
    value: YES
    state: present
  with_items:
    - telegraf
    - influxdb
    - kapacitor
  tags:
    - configuration
    - monitoring
