---
- name: Install packages for monitoring
  pkgng:
    name:
      - telegraf
      - influxdb
      - kapacitor
      - smartmontools
    state: present
  tags:
    - packages
    - monitoring
  
- name: Configure montitoring services
  sysrc:
    name: "{{ item }}_enable"
    value: YES
    state: present
  with_items:
    - telegraf
    - influxdb
    - kapacitor
  tags:
    - configuration
    - monitoring


- name: allow telegraf to do useful things
  blockinfile:
    path: /usr/local/etc/sudoers
    backup: yes
    block: |
      daemon ALL=(root) NOPASSWD: /usr/local/sbin/smartctl --scan
    create: yes
    owner: root
    group: wheel
    marker: "# {mark} ANSIBLE MANAGED BLOCK :: monitoring"
    validate: 'visudo -cf %s'
    state: present
