- name: load tap module
  kld:
    name: if_tap
    load: true
    boot: false
  tags:
    - configuration
    - networking
    - qemu

- name: enable tap link when opened
  sysctl:
    name: net.link.tap.up_on_open
    value: "1"
    state: present
  tags:
    - configuration
    - networking
    - qemu
