- group:
    name: znc
    gid: 2004
    state: present

- user:
    name: znc
    uid: 2004
    group: znc
    shell: /usr/sbin/nologin
    state: present
    createhome: false

- name: create znc log location
  file:
    path: /data/znc
    state: directory
    owner: root
    group: wheel
    mode: 0750

- name: Install packages for znc
  pkgng:
    name:
      - znc
      - zfs-stats
    autoremove: yes
    state: present
  tags:
    - packages

